"""
ATPRV Supplementary Implementation for SUMO + TraCI + Python
=============================================================

    B_i(t) : Behavioral compliance
    M_i(t) : Mobility consistency
    C_i(t) : Communication reliability
    H_i(t) : Historical authentication success


Important methodological point
------------------------------
SUMO/TraCI directly provides mobility values such as position, speed,
acceleration and simulation time. Since no network simulator is used,
communication reliability C_i(t) is generated by a lightweight Python
communication model. The model estimates packet reception probability from:

    1. vehicle-to-RSU distance,
    2. configured communication range,
    3. congestion / vehicle density,
    4. optional random wireless loss.

This makes C_i(t) reproducible within the SUMO-TraCI-Python experiment,
but it must be described in the paper as a Python-level communication
abstraction rather than a packet-level PHY/MAC simulation.

The behavioral score B_i(t) is generated from measurable checks:
    - timestamp freshness,
    - replay/duplicate detection,
    - message-rate compliance,
    - speed plausibility,
    - acceleration plausibility,
    - position/mobility plausibility,
    - authentication result.

The historical score H_i(t) is generated from prior authentication and
reverification outcomes maintained by the Python module.

Author may adapt thresholds to the selected road scenario.
"""

from __future__ import annotations

import csv
import math
import random
from collections import defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Optional, Tuple


# ============================================================
# CONFIGURATION
# ============================================================

SUMO_CONFIG = "your_sumo_config.sumocfg"

# RSU location in SUMO Cartesian coordinates.
# Replace these values with the actual RSU coordinate.
RSU_POSITION = (1000.0, 1000.0)

# Time interval for metric calculation
OBSERVATION_WINDOW = 1.0       # seconds

# Communication abstraction
COMMUNICATION_RANGE = 300.0    # meters
BASE_PACKET_SUCCESS = 0.99
MIN_PACKET_SUCCESS = 0.05
DENSITY_REFERENCE = 50         # vehicles around RSU
DENSITY_PENALTY = 0.25         # maximum density-related penalty
RANDOM_WIRELESS_LOSS = 0.02    # baseline stochastic loss

# Mobility / behavior thresholds
MAX_SPEED = 45.0               # m/s (~162 km/h)
MAX_ACCELERATION = 8.0         # m/s^2
MAX_DECELERATION = 10.0        # m/s^2
MAX_POSITION_ERROR = 10.0      # m, normalization threshold
MAX_BEACON_INTERVAL = 1.5      # seconds
MIN_BEACON_INTERVAL = 0.05     # seconds
FRESHNESS_WINDOW = 2.0         # seconds

# Trust model
ETA = 0.20

# Because (1 - ETA) = 0.80, the four weights sum to 0.20
OMEGA_B = 0.05
OMEGA_M = 0.05
OMEGA_C = 0.05
OMEGA_H = 0.05

INITIAL_TRUST = 0.50

# Example ATPRV trust/risk decision thresholds
TAU_ACC = 0.70
TAU_MIN = 0.40
RISK_THRESHOLD = 0.50

# Output
CSV_FILE = "atprv_all_metrics.csv"

# Fixed seed ensures reproducibility of Python communication abstraction
RANDOM_SEED = 2026
random.seed(RANDOM_SEED)


# ============================================================
# DATA STRUCTURES
# ============================================================

@dataclass
class WindowData:
    observed_messages: int = 0
    valid_messages: int = 0

    packets_sent: int = 0
    packets_received: int = 0


@dataclass
class HistoricalData:
    auth_total: int = 0
    auth_success: int = 0

    reverification_total: int = 0
    reverification_success: int = 0


@dataclass
class VehicleData:
    previous_position: Optional[Tuple[float, float]] = None
    previous_speed: Optional[float] = None
    previous_time: Optional[float] = None

    last_message_time: Optional[float] = None
    last_message_id: Optional[str] = None

    window: WindowData = field(default_factory=WindowData)
    history: HistoricalData = field(default_factory=HistoricalData)

    latest_mobility_score: float = 1.0
    latest_behavior_score: float = 1.0
    latest_communication_score: float = 1.0
    latest_history_score: float = 0.5


# ============================================================
# ATPRV METRIC ENGINE
# ============================================================

class ATPRVMetricEngine:

    def __init__(self):
        self.vehicle: Dict[str, VehicleData] = defaultdict(VehicleData)
        self.trust: Dict[str, float] = defaultdict(lambda: INITIAL_TRUST)

    # --------------------------------------------------------
    # Utility
    # --------------------------------------------------------

    @staticmethod
    def clip01(value: float) -> float:
        return max(0.0, min(1.0, value))

    @staticmethod
    def distance(p1: Tuple[float, float],
                 p2: Tuple[float, float]) -> float:
        return math.hypot(p1[0] - p2[0], p1[1] - p2[1])

    # ========================================================
    # 1. M_i(t): MOBILITY CONSISTENCY
    # ========================================================

    def compute_mobility_score(
        self,
        veh_id: str,
        sim_time: float,
        position: Tuple[float, float],
        speed: float,
    ) -> float:

        data = self.vehicle[veh_id]

        if (
            data.previous_position is None
            or data.previous_speed is None
            or data.previous_time is None
        ):
            data.previous_position = position
            data.previous_speed = speed
            data.previous_time = sim_time
            data.latest_mobility_score = 1.0
            return 1.0

        dt = sim_time - data.previous_time

        if dt <= 0:
            return data.latest_mobility_score

        actual_displacement = self.distance(
            position,
            data.previous_position
        )

        predicted_displacement = data.previous_speed * dt

        deviation = abs(
            actual_displacement - predicted_displacement
        )

        M = 1.0 - min(
            1.0,
            deviation / MAX_POSITION_ERROR
        )

        M = self.clip01(M)

        data.previous_position = position
        data.previous_speed = speed
        data.previous_time = sim_time
        data.latest_mobility_score = M

        return M

    # ========================================================
    # 2. B_i(t): BEHAVIORAL COMPLIANCE
    # ========================================================

    def process_behavior_message(
        self,
        veh_id: str,
        sim_time: float,
        message_timestamp: float,
        message_id: str,
        speed: float,
        acceleration: float,
        authentication_valid: bool,
        mobility_score: float,
    ) -> bool:

        data = self.vehicle[veh_id]

        data.window.observed_messages += 1

        # ----------------------------------------------------
        # Check 1: freshness
        # ----------------------------------------------------
        freshness_ok = (
            abs(sim_time - message_timestamp)
            <= FRESHNESS_WINDOW
        )

        # ----------------------------------------------------
        # Check 2: replay / duplicate message
        # ----------------------------------------------------
        no_replay = (
            data.last_message_id is None
            or message_id != data.last_message_id
        )

        # ----------------------------------------------------
        # Check 3: message generation rate
        # ----------------------------------------------------
        if data.last_message_time is None:
            rate_ok = True
        else:
            interval = sim_time - data.last_message_time

            rate_ok = (
                MIN_BEACON_INTERVAL
                <= interval
                <= MAX_BEACON_INTERVAL
            )

        # ----------------------------------------------------
        # Check 4: speed plausibility
        # ----------------------------------------------------
        speed_ok = (
            0.0 <= speed <= MAX_SPEED
        )

        # ----------------------------------------------------
        # Check 5: acceleration plausibility
        # ----------------------------------------------------
        acceleration_ok = (
            -MAX_DECELERATION
            <= acceleration
            <= MAX_ACCELERATION
        )

        # ----------------------------------------------------
        # Check 6: position/mobility plausibility
        # ----------------------------------------------------
        mobility_ok = (
            mobility_score >= 0.50
        )

        # ----------------------------------------------------
        # Check 7: LWR / protocol authentication
        # ----------------------------------------------------
        auth_ok = authentication_valid

        valid = all(
            [
                freshness_ok,
                no_replay,
                rate_ok,
                speed_ok,
                acceleration_ok,
                mobility_ok,
                auth_ok,
            ]
        )

        if valid:
            data.window.valid_messages += 1

        data.last_message_id = message_id
        data.last_message_time = sim_time

        return valid

    def compute_behavior_score(
        self,
        veh_id: str
    ) -> float:

        data = self.vehicle[veh_id]

        if data.window.observed_messages == 0:
            B = data.latest_behavior_score
        else:
            B = (
                data.window.valid_messages
                / data.window.observed_messages
            )

        B = self.clip01(B)
        data.latest_behavior_score = B

        return B

    # ========================================================
    # 3. C_i(t): COMMUNICATION RELIABILITY
    # ========================================================

    def packet_success_probability(
        self,
        distance_to_rsu: float,
        nearby_vehicle_count: int,
    ) -> float:
        """
        Lightweight communication abstraction for a SUMO-only experiment.

        Reception probability decreases with:
            - distance from RSU
            - congestion / vehicle density
            - baseline wireless loss
        """

        if distance_to_rsu >= COMMUNICATION_RANGE:
            return MIN_PACKET_SUCCESS

        normalized_distance = (
            distance_to_rsu
            / COMMUNICATION_RANGE
        )

        # Quadratic distance degradation
        distance_factor = (
            1.0 - normalized_distance ** 2
        )

        density_ratio = min(
            1.0,
            nearby_vehicle_count
            / DENSITY_REFERENCE
        )

        density_factor = (
            1.0 - DENSITY_PENALTY * density_ratio
        )

        probability = (
            BASE_PACKET_SUCCESS
            * distance_factor
            * density_factor
            * (1.0 - RANDOM_WIRELESS_LOSS)
        )

        return max(
            MIN_PACKET_SUCCESS,
            min(1.0, probability)
        )

    def simulate_packet_transmission(
        self,
        veh_id: str,
        vehicle_position: Tuple[float, float],
        nearby_vehicle_count: int,
    ) -> Tuple[bool, float]:

        data = self.vehicle[veh_id]

        data.window.packets_sent += 1

        d = self.distance(
            vehicle_position,
            RSU_POSITION
        )

        success_probability = (
            self.packet_success_probability(
                d,
                nearby_vehicle_count
            )
        )

        received = (
            random.random()
            <= success_probability
        )

        if received:
            data.window.packets_received += 1

        return received, success_probability

    def compute_communication_score(
        self,
        veh_id: str
    ) -> float:

        data = self.vehicle[veh_id]

        if data.window.packets_sent == 0:
            C = data.latest_communication_score
        else:
            C = (
                data.window.packets_received
                / data.window.packets_sent
            )

        C = self.clip01(C)
        data.latest_communication_score = C

        return C

    # ========================================================
    # 4. H_i(t): HISTORICAL AUTHENTICATION SUCCESS
    # ========================================================

    def record_authentication(
        self,
        veh_id: str,
        success: bool
    ) -> None:

        history = self.vehicle[veh_id].history

        history.auth_total += 1

        if success:
            history.auth_success += 1

    def record_reverification(
        self,
        veh_id: str,
        success: bool
    ) -> None:

        history = self.vehicle[veh_id].history

        history.reverification_total += 1

        if success:
            history.reverification_success += 1

    def compute_history_score(
        self,
        veh_id: str
    ) -> float:

        data = self.vehicle[veh_id]
        history = data.history

        total = (
            history.auth_total
            + history.reverification_total
        )

        success = (
            history.auth_success
            + history.reverification_success
        )

        if total == 0:
            H = 0.50
        else:
            H = success / total

        H = self.clip01(H)
        data.latest_history_score = H

        return H

    # ========================================================
    # TRUST UPDATE
    # ========================================================

    def update_trust(
        self,
        veh_id: str,
        B: float,
        M: float,
        C: float,
        H: float
    ) -> float:

        old_trust = self.trust[veh_id]

        new_trust = (
            (1.0 - ETA) * old_trust
            + OMEGA_B * B
            + OMEGA_M * M
            + OMEGA_C * C
            + OMEGA_H * H
        )

        new_trust = self.clip01(new_trust)

        self.trust[veh_id] = new_trust

        return new_trust

    # ========================================================
    # EXAMPLE PREDICTIVE RISK
    # ========================================================

    def compute_simple_risk(
        self,
        trust: float,
        B: float,
        M: float,
        C: float
    ) -> float:
        """
        Example observable risk mapping for demonstration.

        Replace with the exact ATPRV risk variables
        Phi_i(t), Theta_i(t), Gamma_i(t) used in the manuscript
        if those signals are separately implemented.
        """

        behavioral_anomaly = 1.0 - B
        communication_irregularity = 1.0 - C
        mobility_deviation = 1.0 - M

        risk = (
            0.25 * (1.0 - trust)
            + 0.25 * behavioral_anomaly
            + 0.25 * communication_irregularity
            + 0.25 * mobility_deviation
        )

        return self.clip01(risk)

    def decision(
        self,
        trust: float,
        risk: float
    ) -> str:

        if trust < TAU_MIN:
            return "Reject"

        if trust >= TAU_ACC and risk < RISK_THRESHOLD:
            return "Accept"

        return "Reverify"

    # ========================================================
    # RESET WINDOW
    # ========================================================

    def reset_observation_window(
        self,
        veh_id: str
    ) -> None:

        self.vehicle[veh_id].window = WindowData()


# ============================================================
# CSV LOGGER
# ============================================================

def write_csv(
    sim_time: float,
    veh_id: str,
    B: float,
    M: float,
    C: float,
    H: float,
    trust: float,
    risk: float,
    decision: str,
    communication_probability: float,
):
    path = Path(CSV_FILE)
    first_write = not path.exists()

    with path.open(
        "a",
        newline="",
        encoding="utf-8"
    ) as file:

        writer = csv.writer(file)

        if first_write:
            writer.writerow(
                [
                    "time_s",
                    "vehicle_id",
                    "B_behavior",
                    "M_mobility",
                    "C_communication",
                    "H_history",
                    "trust",
                    "risk",
                    "decision",
                    "packet_success_probability",
                ]
            )

        writer.writerow(
            [
                f"{sim_time:.3f}",
                veh_id,
                f"{B:.6f}",
                f"{M:.6f}",
                f"{C:.6f}",
                f"{H:.6f}",
                f"{trust:.6f}",
                f"{risk:.6f}",
                decision,
                f"{communication_probability:.6f}",
            ]
        )


# ============================================================
# DEMONSTRATION AUTHENTICATION FUNCTION
# ============================================================

def atprv_authentication_result(
    veh_id: str,
    sim_time: float
) -> bool:
    """
    Replace this function with the actual ATPRV LWR verification:

        ||W_i - (Y_i + alpha_i P_i)||_infinity <= tau

    For demonstration purposes, legitimate vehicles pass authentication.
    A deterministic pattern introduces occasional failures so that H_i(t)
    and B_i(t) vary during testing.

    DO NOT claim this demonstration function is the cryptographic
    implementation in the paper. Replace it with your actual LWR routine
    for the final experiment.
    """

    marker = (
        sum(ord(ch) for ch in veh_id)
        + int(sim_time)
    )

    return marker % 23 != 0


# ============================================================
# SUMO / TRACI MAIN LOOP
# ============================================================

def run_atprv_sumo():

    try:
        import traci
    except ImportError:
        raise SystemExit(
            "TraCI not found. Install/configure SUMO Python tools first."
        )

    engine = ATPRVMetricEngine()

    # Check trust normalization
    coefficient_sum = (
        (1.0 - ETA)
        + OMEGA_B
        + OMEGA_M
        + OMEGA_C
        + OMEGA_H
    )

    if abs(coefficient_sum - 1.0) > 1e-9:
        raise ValueError(
            "Trust coefficients must sum to 1."
        )

    traci.start(
        [
            "sumo",
            "-c",
            SUMO_CONFIG
        ]
    )

    last_metric_time = 0.0

    # Store latest communication probability
    latest_p_success = defaultdict(lambda: 1.0)

    try:

        while (
            traci.simulation.getMinExpectedNumber()
            > 0
        ):

            traci.simulationStep()

            sim_time = (
                traci.simulation.getTime()
            )

            vehicle_ids = list(
                traci.vehicle.getIDList()
            )

            # ------------------------------------------------
            # Number of vehicles near RSU
            # ------------------------------------------------
            vehicles_near_rsu = 0

            for vid in vehicle_ids:

                pos = (
                    traci.vehicle.getPosition(vid)
                )

                if (
                    engine.distance(
                        pos,
                        RSU_POSITION
                    )
                    <= COMMUNICATION_RANGE
                ):
                    vehicles_near_rsu += 1

            # ------------------------------------------------
            # Process each vehicle
            # ------------------------------------------------
            for veh_id in vehicle_ids:

                position = (
                    traci.vehicle.getPosition(
                        veh_id
                    )
                )

                speed = (
                    traci.vehicle.getSpeed(
                        veh_id
                    )
                )

                acceleration = (
                    traci.vehicle.getAcceleration(
                        veh_id
                    )
                )

                # ============================================
                # M_i(t): directly from TraCI
                # ============================================
                M = engine.compute_mobility_score(
                    veh_id,
                    sim_time,
                    position,
                    speed
                )

                # ============================================
                # Simulated beacon / authentication message
                # ============================================
                message_timestamp = sim_time

                message_id = (
                    f"{veh_id}_{sim_time:.3f}"
                )

                # Actual ATPRV verification should replace
                # this demonstration function.
                auth_success = (
                    atprv_authentication_result(
                        veh_id,
                        sim_time
                    )
                )

                engine.record_authentication(
                    veh_id,
                    auth_success
                )

                # ============================================
                # B_i(t): protocol + mobility observations
                # ============================================
                engine.process_behavior_message(
                    veh_id=veh_id,
                    sim_time=sim_time,
                    message_timestamp=message_timestamp,
                    message_id=message_id,
                    speed=speed,
                    acceleration=acceleration,
                    authentication_valid=auth_success,
                    mobility_score=M,
                )

                # ============================================
                # C_i(t): Python communication abstraction
                # ============================================
                received, p_success = (
                    engine.simulate_packet_transmission(
                        veh_id,
                        position,
                        vehicles_near_rsu
                    )
                )

                latest_p_success[
                    veh_id
                ] = p_success

                # Optional:
                # if packet was not received, the RSU would
                # not actually process the message.
                #
                # For a stricter event-order implementation,
                # perform reception simulation BEFORE behavior
                # and authentication processing.

            # ------------------------------------------------
            # Calculate metrics once per observation window
            # ------------------------------------------------
            if (
                sim_time - last_metric_time
                >= OBSERVATION_WINDOW
            ):

                print(
                    "\nTime:",
                    round(sim_time, 2)
                )

                for veh_id in vehicle_ids:

                    B = (
                        engine.compute_behavior_score(
                            veh_id
                        )
                    )

                    M = (
                        engine.vehicle[
                            veh_id
                        ].latest_mobility_score
                    )

                    C = (
                        engine.compute_communication_score(
                            veh_id
                        )
                    )

                    H = (
                        engine.compute_history_score(
                            veh_id
                        )
                    )

                    trust = engine.update_trust(
                        veh_id,
                        B,
                        M,
                        C,
                        H
                    )

                    risk = (
                        engine.compute_simple_risk(
                            trust,
                            B,
                            M,
                            C
                        )
                    )

                    decision = (
                        engine.decision(
                            trust,
                            risk
                        )
                    )

                    print(
                        veh_id,
                        f"B={B:.3f}",
                        f"M={M:.3f}",
                        f"C={C:.3f}",
                        f"H={H:.3f}",
                        f"T={trust:.3f}",
                        f"R={risk:.3f}",
                        decision
                    )

                    write_csv(
                        sim_time,
                        veh_id,
                        B,
                        M,
                        C,
                        H,
                        trust,
                        risk,
                        decision,
                        latest_p_success[
                            veh_id
                        ]
                    )

                    engine.reset_observation_window(
                        veh_id
                    )

                last_metric_time = sim_time

    finally:
        traci.close()


# ============================================================
# STAND-ALONE TEST WITHOUT SUMO
# ============================================================

def test_metric_engine():

    engine = ATPRVMetricEngine()

    veh_id = "veh0"

    # Mobility
    engine.compute_mobility_score(
        veh_id,
        0.0,
        (100.0, 100.0),
        15.0
    )

    M = engine.compute_mobility_score(
        veh_id,
        1.0,
        (114.5, 100.0),
        15.0
    )

    # Behavioral samples
    for index in range(20):

        engine.process_behavior_message(
            veh_id=veh_id,
            sim_time=index * 0.1,
            message_timestamp=index * 0.1,
            message_id=f"m{index}",
            speed=15.0,
            acceleration=0.5,
            authentication_valid=(
                index not in {7, 16}
            ),
            mobility_score=M,
        )

    # Communication samples
    for _ in range(50):

        engine.simulate_packet_transmission(
            veh_id,
            (150.0, 100.0),
            nearby_vehicle_count=20
        )

    # Authentication history
    for i in range(50):

        engine.record_authentication(
            veh_id,
            success=(i < 47)
        )

    B = engine.compute_behavior_score(
        veh_id
    )

    C = engine.compute_communication_score(
        veh_id
    )

    H = engine.compute_history_score(
        veh_id
    )

    trust = engine.update_trust(
        veh_id,
        B,
        M,
        C,
        H
    )

    risk = engine.compute_simple_risk(
        trust,
        B,
        M,
        C
    )

    decision = engine.decision(
        trust,
        risk
    )

    print("\nStandalone ATPRV metric test")
    print("----------------------------")
    print(f"B_i(t) = {B:.4f}")
    print(f"M_i(t) = {M:.4f}")
    print(f"C_i(t) = {C:.4f}")
    print(f"H_i(t) = {H:.4f}")
    print(f"T_i(t+1) = {trust:.4f}")
    print(f"R_i(t) = {risk:.4f}")
    print(f"Decision = {decision}")


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    # First verify the metric calculations without SUMO.
    test_metric_engine()

    # Then uncomment the following line for the real SUMO run:
    #
    # run_atprv_sumo()
