from __future__ import annotations
import csv
from collections import defaultdict
from pathlib import Path

TAU_MIN = 0.40
TAU_ACC = 0.70
STATES = ("L", "M", "H")

INPUT_CSV = "atprv_all_metrics.csv"
OUTPUT_COUNTS = "atprv_markov_transition_counts.csv"
OUTPUT_PROBS = "atprv_markov_transition_probabilities.csv"
OUTPUT_STATES = "atprv_vehicle_state_sequences.csv"


def trust_to_state(trust, tau_min=TAU_MIN, tau_acc=TAU_ACC):
    """Map ATPRV continuous trust value T_i(t) to L/M/H state."""
    if not 0.0 <= trust <= 1.0:
        raise ValueError("Trust must lie in [0,1].")

    if trust < tau_min:
        return "L"
    elif trust < tau_acc:
        return "M"
    else:
        return "H"


class MarkovTrustEstimator:
    def __init__(self, tau_min=TAU_MIN, tau_acc=TAU_ACC):
        self.tau_min = tau_min
        self.tau_acc = tau_acc

        self.previous_state = {}
        self.sequence = defaultdict(list)

        self.counts = {
            a: {b: 0 for b in STATES}
            for a in STATES
        }

    def update(self, vehicle_id, trust, sim_time):
        """
        Call once after every ATPRV trust update.

        Example:
            T_i(t)   = 0.62 -> M
            T_i(t+1) = 0.74 -> H

        Then N_MH is incremented by one.
        """
        state = trust_to_state(
            trust,
            self.tau_min,
            self.tau_acc
        )

        self.sequence[vehicle_id].append(
            (sim_time, trust, state)
        )

        if vehicle_id in self.previous_state:
            old_state = self.previous_state[vehicle_id]
            self.counts[old_state][state] += 1

        self.previous_state[vehicle_id] = state

        return state

    def probabilities(self):
        """
        P_ab = N_ab / sum_c N_ac
        """
        P = {
            a: {b: 0.0 for b in STATES}
            for a in STATES
        }

        for a in STATES:
            row_total = sum(self.counts[a].values())

            if row_total > 0:
                for b in STATES:
                    P[a][b] = (
                        self.counts[a][b] / row_total
                    )

        return P

    def print_results(self):
        P = self.probabilities()

        print("\nTransition-count matrix N")
        print("          To-L   To-M   To-H")

        for a in STATES:
            print(
                f"From-{a}: "
                f"{self.counts[a]['L']:5d} "
                f"{self.counts[a]['M']:6d} "
                f"{self.counts[a]['H']:6d}"
            )

        print("\nTransition-probability matrix P")
        print("             L        M        H")

        for a in STATES:
            print(
                f"{a}: "
                f"{P[a]['L']:.4f}   "
                f"{P[a]['M']:.4f}   "
                f"{P[a]['H']:.4f}"
            )

    def save_results(self):
        P = self.probabilities()

        with open(
            OUTPUT_COUNTS, "w", newline="", encoding="utf-8"
        ) as f:
            writer = csv.writer(f)
            writer.writerow(
                ["from_state", "to_L", "to_M", "to_H", "row_total"]
            )

            for a in STATES:
                row_total = sum(self.counts[a].values())
                writer.writerow([
                    a,
                    self.counts[a]["L"],
                    self.counts[a]["M"],
                    self.counts[a]["H"],
                    row_total
                ])

        with open(
            OUTPUT_PROBS, "w", newline="", encoding="utf-8"
        ) as f:
            writer = csv.writer(f)
            writer.writerow(
                ["from_state", "P_to_L", "P_to_M", "P_to_H", "row_sum"]
            )

            for a in STATES:
                row_sum = sum(P[a].values())
                writer.writerow([
                    a,
                    f"{P[a]['L']:.8f}",
                    f"{P[a]['M']:.8f}",
                    f"{P[a]['H']:.8f}",
                    f"{row_sum:.8f}"
                ])

        with open(
            OUTPUT_STATES, "w", newline="", encoding="utf-8"
        ) as f:
            writer = csv.writer(f)
            writer.writerow(
                ["vehicle_id", "time_s", "trust", "state"]
            )

            for veh_id, values in self.sequence.items():
                for sim_time, trust, state in values:
                    writer.writerow([
                        veh_id,
                        f"{sim_time:.6f}",
                        f"{trust:.8f}",
                        state
                    ])


def estimate_from_csv(input_csv=INPUT_CSV):
    """
    Post-process ATPRV trust values already generated by the
    SUMO-TraCI-Python simulation.

    Expected CSV columns:
        time_s, vehicle_id, trust
    """
    estimator = MarkovTrustEstimator()

    rows_by_vehicle = defaultdict(list)

    with open(input_csv, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        required = {"time_s", "vehicle_id", "trust"}

        if not required.issubset(reader.fieldnames or []):
            raise ValueError(
                "CSV must contain time_s, vehicle_id, and trust columns."
            )

        for row in reader:
            rows_by_vehicle[row["vehicle_id"]].append(
                (
                    float(row["time_s"]),
                    float(row["trust"])
                )
            )

    # Count only consecutive states belonging to the same vehicle.
    for veh_id, values in rows_by_vehicle.items():
        values.sort(key=lambda x: x[0])

        for sim_time, trust in values:
            estimator.update(
                veh_id,
                trust,
                sim_time
            )

    return estimator


def demonstration():
    """
    Demonstration:
    tau_min = 0.40
    tau_acc = 0.70

    V1 trust sequence:
        0.35(L), 0.46(M), 0.61(M), 0.74(H), 0.77(H), 0.65(M)

    transitions:
        L->M
        M->M
        M->H
        H->H
        H->M
    """

    estimator = MarkovTrustEstimator()

    values = [
        (1.0, 0.35),
        (2.0, 0.46),
        (3.0, 0.61),
        (4.0, 0.74),
        (5.0, 0.77),
        (6.0, 0.65)
    ]

    for sim_time, trust in values:
        estimator.update(
            "V1",
            trust,
            sim_time
        )

    estimator.print_results()


# ============================================================
# INSERT THIS PART IN THE EXISTING SUMO-TRACI ATPRV PROGRAM
# ============================================================

"""
Before the SUMO simulation loop:

    markov = MarkovTrustEstimator(
        tau_min=TAU_MIN,
        tau_acc=TAU_ACC
    )


After the four metrics B, M, C, H are calculated:

    trust = engine.update_trust(
        veh_id,
        B,
        M,
        C,
        H
    )

    state = markov.update(
        vehicle_id=veh_id,
        trust=trust,
        sim_time=sim_time
    )


At the end of the SUMO simulation:

    markov.print_results()
    markov.save_results()
"""


if __name__ == "__main__":

    if Path(INPUT_CSV).exists():
        model = estimate_from_csv(INPUT_CSV)
        model.print_results()
        model.save_results()

        print("\nSaved:")
        print(OUTPUT_COUNTS)
        print(OUTPUT_PROBS)
        print(OUTPUT_STATES)

    else:
        print(
            "atprv_all_metrics.csv not found; running demonstration."
        )
        demonstration()
